//
// Created by MyPC on 2024/05/15.
//

#ifndef PALMVEINDEMO_COM_MAXVISION_UVCXU_UVCLIGHT_H
#define PALMVEINDEMO_COM_MAXVISION_UVCXU_UVCLIGHT_H


class com_maxvision_uvcxu_UVCLight {

};


#endif //PALMVEINDEMO_COM_MAXVISION_UVCXU_UVCLIGHT_H
